// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5y_M6gC3Tr4DJ1e0COA7esWgfBiRdVB8',
    appId: '1:649566851343:web:68758f0e05c063e2186e7a',
    messagingSenderId: '649566851343',
    projectId: 'daily-stories-60463',
    authDomain: 'daily-stories-60463.firebaseapp.com',
    storageBucket: 'daily-stories-60463.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG1iH3kPtjOra2tHV4oflr3tIWltEhPx4',
    appId: '1:649566851343:android:1ef79cef5b24100a186e7a',
    messagingSenderId: '649566851343',
    projectId: 'daily-stories-60463',
    storageBucket: 'daily-stories-60463.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-_Q7VFAfUiRaod3Ny9EOhuLqJfHFSjzg',
    appId: '1:649566851343:ios:5b9379829ca62906186e7a',
    messagingSenderId: '649566851343',
    projectId: 'daily-stories-60463',
    storageBucket: 'daily-stories-60463.firebasestorage.app',
    iosBundleId: 'com.example.dailyDairies',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-_Q7VFAfUiRaod3Ny9EOhuLqJfHFSjzg',
    appId: '1:649566851343:ios:5b9379829ca62906186e7a',
    messagingSenderId: '649566851343',
    projectId: 'daily-stories-60463',
    storageBucket: 'daily-stories-60463.firebasestorage.app',
    iosBundleId: 'com.example.dailyDairies',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5y_M6gC3Tr4DJ1e0COA7esWgfBiRdVB8',
    appId: '1:649566851343:web:ecdb90d53c9327ec186e7a',
    messagingSenderId: '649566851343',
    projectId: 'daily-stories-60463',
    authDomain: 'daily-stories-60463.firebaseapp.com',
    storageBucket: 'daily-stories-60463.firebasestorage.app',
  );
}
